INSERT into whosit.staff (first_name, last_name, gender, picture_url) VALUES
   ('John', 'Smith', 'MALE', 'url'),
   ('Davy', 'Smith', 'MALE', 'url'),
   ('Eric', 'North', 'MALE', 'url'),
   ('Abigail', 'North', 'FEMALE', 'url'),
   ('Amy', 'Whinehouse', 'FEMALE', 'dsfhjsdjhfjsd'),
   ('Sam', 'Smith', 'MALE', 'url'),
   ('Boyle', 'Smith', 'MALE', 'url'),
   ('Mark', 'North', 'MALE', 'url'),
   ('Pink', 'North', 'FEMALE', 'url'),
   ('Beyonce', 'Smith', 'FEMALE', 'dsfhjsdjhfjsd'),
   ('Mike', 'Magic', 'MALE', 'url'),
   ('Arnold', 'schwarzenegger', 'MALE', 'url'),
   ('Robert', 'De Niro', 'MALE', 'url'),
   ('Merryl', 'Sheep', 'FEMALE', 'url'),
   ('Keira', 'Nightley', 'FEMALE', 'dsfhjsdjhfjsd');
